# Generated by Django 6.0.7 on 2026-07-15 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='wilaya_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='locations.wilaya'),
        ),
    ]
