# Generated by Django 6.0.7 on 2026-07-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_rename_wilaya_id_commune_wilaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='ar_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
