# Generated by Django 6.0.7 on 2026-07-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_commune_ar_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='wilaya',
            new_name='wilaya_id',
        ),
    ]
