# Generated by Django 6.0.7 on 2026-07-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_rename_wilaya_commune_wilaya_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='wilaya_id',
            new_name='wilaya',
        ),
    ]
