# Generated by Django 6.0.7 on 2026-08-03 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_statushistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statushistory',
            old_name='chenged_at',
            new_name='changed_at',
        ),
        migrations.RemoveField(
            model_name='statushistory',
            name='changes',
        ),
        migrations.AddField(
            model_name='statushistory',
            name='new_status',
            field=models.CharField(default='pending', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statushistory',
            name='previous_status',
            field=models.CharField(default='confirmed', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('notregistered', 'NOTREGISTERED'), ('registered', 'REGISTERED'), ('dispatched', 'DISPATCHED'), ('in_transit', 'IN_TRANSIT'), ('delivered', 'DELIVERED'), ('returned', 'RETURNED')], default='notregistered', max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('unreachable', 'UNREACHABLE'), ('postponed', 'POSTPONED'), ('cancelled', 'CANCELLED')], default='pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_history', to='orders.order'),
        ),
    ]
