# Generated by Django 6.0.7 on 2026-08-09 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_rename_wilaya_id_commune_wilaya'),
        ('orders', '0004_alter_order_delivery_cost_alter_order_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='locations.commune'),
        ),
    ]
