# Generated by Django 6.0.7 on 2026-08-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
