# Generated by Django 6.0.7 on 2026-08-02 09:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_rename_wilaya_id_commune_wilaya'),
        ('products', '0003_alter_product_slug_color_productimage_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('unreachable', 'UNREACHABLE'), ('postponed', 'POSTPONED'), ('cancelled', 'CANCELLED')], max_length=64)),
                ('delivery_status', models.CharField(choices=[('registered', 'REGISTERED'), ('dispatched', 'DISPATCHED'), ('in_transit', 'IN_TRANSIT'), ('delivered', 'DELIVERED'), ('returned', 'RETURNED')], max_length=64)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_str', models.CharField(max_length=250)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size_str', models.CharField(blank=True, max_length=250, null=True)),
                ('size_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color_str', models.CharField(blank=True, max_length=64, null=True)),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.color')),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='locations.commune')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.size')),
                ('wilaya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='locations.wilaya')),
            ],
        ),
    ]
