# Generated by Django 6.0.7 on 2026-08-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
